services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chat_postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Chat Server Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://chatuser:chatpass@postgres:5432/chatdb
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      JWT_SECRET: xyhdkllkdjf#78djkhfodifakljdfodkf
      JWT_EXPIRATION: 3600
      REFRESH_TOKEN_EXPIRATION: 2592000
      RUST_LOG: info
      ENVIRONMENT: production
      RUN_MIGRATIONS: "false" # skip if you don't want to run migrations, set true if you want to run migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
